logging:
  level:
    com.self.sprintboot.learning.apigateway: DEBUG

skip:
 security: N            

spring:  
  application:
    name: agreements  
      # main:
  #  allow-bean-definition-overriding: true
  profiles:
    active: default
  cloud:
    config:
      uri: http://localhost:9296/
  security:
    oauth2:
      resourceserver:
        jwt:         
         issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_zgkHvtA9m 


management:
  security:
    enabled: false

service:
  controller:
    doc: This controller used for finding agreement information with varios GET operations.
  searhcagreements:
    doc: Search agreements by first name, last name, agreement id, social security, fate fo birth or agreement number in given store, line of business or gloabl

